### ISSUE TITLE
[Akami::WSSE::Certs] Add support for in-memory certificates and private keys

### ISSUE THREAD

**Issue by toncid** [savonrb/akami#19]
Hello,

This class accepts only file paths for `cert_file` and `private_key_file`, whereas there are situations where those can be provided as in-memory strings.

Maybe the constructor should allow setting `@cert` and `@private_key` fields directly and thus avoid the `||=` check and assignment in attribute accessors?

Thanks!

**Comment by tjarratt** [comment]
That's a pretty reasonable suggestion, @toncid. My personal preference is to always separate my application's concerns (ie: what it does) from its data (e.g.: what it uses to do that task), but I can easily imagine some scenario where you receive a private key from some external service and it's unwieldy to write it to a temporary file just to make a request.

I'm not entirely sure that exposing the instance variables is the best way to go, because the consumer needs to know either to read from a file first. Maybe changing the setters to check if the provided argument looks like a file system path, then falling back and treating it as a string would be better.

Would you be interesting in submitting a pull request for this?

**Comment by toncid** [comment]
Hello, the pull request #20 is submitted.

**Comment by tjarratt** [comment]
Closed by #20 (thanks again! :smile:)
