### ISSUE TITLE
Release changes on master?

### ISSUE THREAD

**Issue by owst** [savonrb/akami#45]
Hi @olleolleolle - you seem to have merged a few PRs against this repo "recently" 😄  - are you able to release a new version of the gem with these changes included? I'm specifically interested in https://github.com/savonrb/akami/pull/35

Thanks!

**Comment by a-lavis** [comment]
I'm also interesting in using #35!

While trying to upgrade to Rails 7.1, I ran into this issue:
https://github.com/rails/rails/issues/49457#issuecomment-1743135412
but with `akami` instead of the `config` gem.

Doing:
```ruby
gem 'akami', git: 'https://github.com/savonrb/akami.git', branch: 'master'
```
fixed the issue for me.

---

Because the `akami` repo hasn't had an update in quite a while, I thought I'd tag @pcai since it looks like they are a maintainer of the [savonrb](https://github.com/savonrb) org.  Thanks maintainers for all your hard work!

**Comment by pcai** [comment]
I'll take a look but its been a moment since the last release and there might be some rust to shake off. Thanks for your patience on this.

**Comment by pcai** [comment]
https://github.com/savonrb/akami/releases/tag/v1.3.2
